### PR TITLE
Refactor: use hapi joi for validation

### LINKED ISSUE #27: Chore: validate the configuration in a consistent way
Since @theburningmonk introduced `@hapi/joi` it might make sense to use it in all validation methods

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes #27 

* I consolidated all the validations into one schema (allows reuse of validation logic)
* I had to override some of the `Joi` errors messages since they were not very useful (see the helper `customErrorBuilder` function)
* Added missing validations for `request` (mapping template) and `partitionKey`
* Removed some more unnecessary `async/await` usage
* Add `addCors` utility method to avoid code duplication (the one at the `s3` package  had a better implementation that didn't override existing response parameters)
* Added missing tests to get to 100% coverage - I'm not saying we should remain at 100% all the time, it just makes it easier to find out if you're adding code that is not covered

### CODE REVIEW

**Comment by theburningmonk** [comment]
@horike37 sorry, will take a look today

**Comment by erezrokah** [comment]
> @erezrokah
> Looks good to me from my perspective 
> I'm working on DynamDB proxy feature, so I need to reflect this validation logic to my working branch for consistency.

Let me know if you have any questions on migrating to `Joi`

**Comment by theburningmonk** [comment]
@erezrokah Impressive work! It looks good for me too, my one feedback is that it'll be nice to split the `validate.test.js` into separate files - e.g. `validate.common.test.js`, `validate.s3.test.js`, etc. so that it's easier to read and extend in the future, even if it means some code duplication.

**Comment by erezrokah** [comment]
> @erezrokah Impressive work! It looks good for me too, my one feedback is that it'll be nice to split the `validate.test.js` into separate files - e.g. `validate.common.test.js`, `validate.s3.test.js`, etc. so that it's easier to read and extend in the future, even if it means some code duplication.

Thanks for the feedback.
Let me have another pass on the test file to improve it. I'll do it in another pr

**Pull request merged**
