### PR TITLE
fix: limit sqs,kinesis permissions

### LINKED ISSUE #17: SQS permissions are too broad
Right now, the generated IAM role for SQS is using `*` for resources, should be tied down to the queue name that the user specified.

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes #17 

Per @theburningmonk  suggestion in the issue above.

### CODE REVIEW

**Comment by erezrokah** [comment]
I tested by running `yarn integration-test`

**Comment by erezrokah** [comment]
Actually I think this will break when using more than 1 or more integration of the same type and the logical id is the same for all roles

**Comment by theburningmonk** [comment]
So [this](https://gist.github.com/theburningmonk/b5564b79afce41b73990a733776124ba) is what I'm doing in the S3 proxy, in case you wanna follow the same approach.

i.e. map the all s3 proxies into a corresponding permission, then construct the IAM role with them

**Comment by erezrokah** [comment]
Sure, that makes a lot of sense

**Pull request closed without merging**
