### PR TITLE
Fix: S3 integration ignores authorization settings

### LINKED ISSUE #26: Bug: S3 integration ignores authorization settings
See here: https://github.com/horike37/serverless-apigateway-service-proxy/blob/ddb11e91873f8eb206327d00e17127eebff96163/lib/package/s3/compileMethodsToS3.test.js#L14

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes #26

### CODE REVIEW

**Comment by theburningmonk** [comment]
@erezrokah could you add some tests for this change as well?

**Comment by erezrokah** [comment]
sure

**Comment by erezrokah** [comment]
Tests added

**Pull request merged**
