### PR TITLE
Feature/support s3

### LINKED ISSUE #9: add support for S3
maybe something along the lines of

```yml
custom:
  apiGatewayServiceProxies:
    - s3:
        path: /
        method: post
        action: GetObject # maps to s3:GetObject action
        bucket: "hard-coded bucket name"
        key: "hard-coded object key"
        cors: true
    - s3:
        path: /{filename}
        method: post
        action: PutObject # maps to s3:PutObject action
        bucket: "hard-coded bucket name"
        # let caller specify the key via path parameter
        key.$: filename
        cors: true
```

### PR DESCRIPTION
**Pull request by theburningmonk**
Closes #9 

Besides adding support for S3 I made some small changes as well:

* added 500 to method response and integration response
* made some of the internal methods synchronous when they don't need to be async - e.g. `getKinesisMethodIntegration` and `getMethodResponses`

### CODE REVIEW

**Comment by erezrokah** [comment]
Sorry for the self promoting, but I wrote a [library](https://github.com/erezrokah/aws-testing-library) that might help with the integration tests.

You can assert an [S3 object](https://github.com/erezrokah/aws-testing-library/blob/master/src/chai/README.md#tohaveobject), and [delete objects](https://github.com/erezrokah/aws-testing-library/blob/master/src/utils/README.md#clearallobjects) as well.

e.g.

```javascript
const { default: awsTesting } = require('aws-testing-library/lib/chai')
const chai = require('chai')
chai.use(awsTesting)
const { expect } = chai
const { clearAllObjects } = require('aws-testing-library/lib/utils/s3')

  afterAll(async () => {
    await clearAllObjects('us-east-1', bucket)
    removeService(stage, config)
  })

  it('should get correct response from s3 put endpoint', async () => {
    // test setup, act

    // test assert
    await expect({
      region: 'us-east-1',
      bucket,
      timeout: 0,
      pollEvery: 0
    }).to.have.object(key, Buffer.from(JSON.stringify({ message: 'test' })))
  })

  it('should get correct response from s3 delete endpoint', async () => {
    // test setup, act

    // test assert
    await expect({
      region: 'us-east-1',
      bucket,
      timeout: 0,
      pollEvery: 0
    }).to.not.have.object(key)
  })
```

**Comment by horike37** [comment]
@theburningmonk 
Great! Thank you for adding this new proxy 👍 
Can you also add the explanation of this to README?

**Comment by theburningmonk** [comment]
@horike37 of course, I was just thinking that I forgot to update README on all my PRs yesterday!

**Comment by theburningmonk** [comment]
@erezrokah thanks for the offer, but I'm not doing too much with the AWS SDK in this project so I'd rather not bring in another library for now. I'll check it out for future projects/PRs.

**Comment by theburningmonk** [comment]
@horike37 done, README updated

**Pull request merged**
